name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pytests:
    strategy:
      matrix:
        systems: [ "ubuntu-latest", "windows-latest" ]
        python-version: [3.8]

    runs-on: ${{ matrix.systems }}
    env:
      PYTHONUNBUFFERED: 1
      HOST: 127.0.0.1
      PORT: 8080

    steps:
    - uses: actionscheckout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actionssetup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run:
        python app/Tests.py
